# Generated by Django 3.0 on 2022-08-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pin', models.PositiveIntegerField()),
                ('state', models.CharField(choices=[('Purbaanchal', 'Purbaanchal'), ('Madeshperdesh', 'Madeshperdesh'), ('Bagmati Perdesh', 'Bagmati Perdesh'), ('Gandaki perdesh', 'Gandaki Perdesh'), ('Lumbani Perdesh', 'Lumbani Perdesh'), ('Karnali Perdesh', 'Karnali Perdesh'), ('Suderpashim Perdesh', 'Suderpashim Perdesh')], max_length=50)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('job_city', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(blank=True, upload_to='profileimg')),
                ('my_file', models.FileField(blank=True, upload_to='doc')),
            ],
        ),
    ]
